### ISSUE TITLE
UserFollower.follower_id bad naming

### ISSUE THREAD

**Issue by lbighetti** [lbighetti/elixir-phoenix-realworld#32]
`follower_id` represents a author a user is following.
It's more like *following*, not *follower*

**Comment by viniciusilveira** [comment]
I'm looking this issue

**Comment by lbighetti** [comment]
super !
let me know if you need further info, I realize my description is not the greatest :)

**Comment by viniciusilveira** [comment]
I understood that field follower_id not represents wath really should be, an following and not follower. That's why must be renamed from follower_id to following_id.

**Comment by lbighetti** [comment]
yes exactly. 

Even better, perhaps is `followee` 

https://en.oxforddictionaries.com/definition/followee

As a non-native English for me is hard to find the right words sometimes, but this seems appropriate

> 2. A person who is being followed.
