### ISSUE TITLE
Tests for /articles/feed/

### ISSUE THREAD

**Issue by lbighetti** [lbighetti/elixir-phoenix-realworld#33]

**Comment by caironoleto** [comment]
I'm looking this issue ;)

**Comment by caironoleto** [comment]
Sorry! I have no time to see this issue in this week. I will try in the next week :)

**Comment by paulsmal** [comment]
Someone doing this?

**Comment by lbighetti** [comment]
@paulsmal I don't think so, go ahead if you want

**Comment by lbighetti** [comment]
Guys, migrating this to new repo -> https://github.com/gothinkster/elixir-phoenix-realworld-example-app/issues/1
