### ISSUE TITLE
Access-Control-Allow-Origin error 

### ISSUE THREAD

**Issue by mydearxym** [lbighetti/elixir-phoenix-realworld#42]
i download a random realworld frontend framework and change request api to local 4000, but a got
`Access-Control-Allow-Origin` in brower ...

how to enable Access-Control-Allow-Origin in this elixir-phoenix-realworld project ?

thanks!

**Comment by lbighetti** [comment]
Hi @mydearxym,
Can you give me more information so I can try to replicate the issue?
Which frontend are you trying to use ?

I've tested it with
https://github.com/gothinkster/react-redux-realworld-example-app

**Comment by mydearxym** [comment]
False alarm ... sorry it's my own issue with the route part , it works fine 👍

**Comment by lbighetti** [comment]
Super!
cheers!
