### ISSUE TITLE
Elixir's `to_iso8601` does not match Postman's tests

### ISSUE THREAD

**Issue by sotojuan** [lbighetti/elixir-phoenix-realworld#8]
If you pass a `created_at` field to `NaiveDateTime.to_iso8601`, you get a string like this:

`'2017-04-26T15:53:15.511646'`.

The Postman tests take that string and pass it through JavaScript's `toISOString` and checks that both are equal.

`toISOString` returns `2017-04-26T15:53:15.511Z`, which is different. Hence, the tests fail.

Let's find a way to return the correct string!

**Comment by lbighetti** [comment]
Hi @sotojuan !
This has been fixed.
Thanks!
